# -*- coding: utf-8 -*-
# -*- Mode: Python; py-ident-offset: 4 -*-
# vim:ts=4:sw=4:et
'''
rpm definitions

'''

from typing import Any, Dict


RPM_LEAD_MAGIC_NUMBER = b'\xed\xab\xee\xdb'
RPM_HEADER_MAGIC_NUMBER = b'\x8e\xad\xe8'
RPM_ZX_PAYLOAD_MAGIC_NUMBER = b'\xfd\x37\x7A\x58\x5A\x00'
RPM_GZIP_PAYLOAD_MAGIC_NUMBER = b'\x1f\x8b'

RPMTAG_MIN_NUMBER = 0
RPMTAG_MAX_NUMBER = 1146

# signature tags
RPMSIGTAG_SIZE     = 1000
RPMSIGTAG_LEMD5_1  = 1001
RPMSIGTAG_PGP      = 1002
RPMSIGTAG_LEMD5_2  = 1003
RPMSIGTAG_MD5      = 1004
RPMSIGTAG_GPG      = 1005
RPMSIGTAG_PGP5     = 1006


MD5_SIZE = 16  # 16 bytes long
PGP_SIZE = 152  # 152 bytes long


# data types definition
RPM_DATA_TYPE_NULL = 0
RPM_DATA_TYPE_CHAR = 1
RPM_DATA_TYPE_INT8 = 2
RPM_DATA_TYPE_INT16 = 3
RPM_DATA_TYPE_INT32 = 4
RPM_DATA_TYPE_INT64 = 5
RPM_DATA_TYPE_STRING = 6
RPM_DATA_TYPE_BIN = 7
RPM_DATA_TYPE_STRING_ARRAY = 8
RPM_DATA_TYPE_I18NSTRING_TYPE = 9

RPM_DATA_TYPES = (RPM_DATA_TYPE_NULL,
                  RPM_DATA_TYPE_CHAR,
                  RPM_DATA_TYPE_INT8,
                  RPM_DATA_TYPE_INT16,
                  RPM_DATA_TYPE_INT32,
                  RPM_DATA_TYPE_INT64,
                  RPM_DATA_TYPE_STRING,
                  RPM_DATA_TYPE_BIN,
                  RPM_DATA_TYPE_STRING_ARRAY,
                  RPM_DATA_TYPE_I18NSTRING_TYPE)

# https://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/pkgformat.html

RPMTAG_HEADERIMMUTABLE = 63
RPMTAG_HEADERI18NTABLE = 100

# Package info tag values
RPMTAG_NAME = 1000
RPMTAG_VERSION = 1001
RPMTAG_RELEASE = 1002
RPMTAG_SUMMARY = 1004
RPMTAG_DESCRIPTION = 1005
RPMTAG_SIZE = 1009
RPMTAG_DISTRIBUTION = 1010
RPMTAG_VENDOR = 1011
RPMTAG_LICENSE = 1014
RPMTAG_PACKAGER = 1015
RPMTAG_GROUP = 1016
RPMTAG_URL = 1020
RPMTAG_OS = 1021
RPMTAG_ARCH = 1022
RPMTAG_SOURCERPM = 1044
RPMTAG_ARCHIVESIZE = 1046
RPMTAG_RPMVERSION = 1064
RPMTAG_COOKIE = 1094
RPMTAG_DISTURL = 1123
RPMTAG_PAYLOADFORMAT = 1124
RPMTAG_PAYLOADCOMPRESSOR = 1125
RPMTAG_PAYLOADFLAGS = 1126

# Installation tag values
RPMTAG_PREIN = 1023
RPMTAG_POSTIN = 1024
RPMTAG_PREUN = 1025
RPMTAG_POSTUN = 1026
RPMTAG_PREINPROG = 1085
RPMTAG_POSTINPROG = 1086
RPMTAG_PREUNPROG = 1087
RPMTAG_POSTUNPROG = 1088

# File Info Tag Values
RPMTAG_OLDFILENAMES = 1027
RPMTAG_FILESIZES = 1028
RPMTAG_FILEMODES = 1030
RPMTAG_FILERDEVS = 1033
RPMTAG_FILEMTIMES = 1036
RPMTAG_FILEMD5S = 1035
RPMTAG_FILELINKTOS = 1036
RPMTAG_FILEFLAGS = 1037
RPMTAG_FILEUSERNAME = 1039
RPMTAG_FILEGROUPNAME = 1040
RPMTAG_FILEDEVICES = 1095
RPMTAG_FILEINODES = 1096
RPMTAG_FILELANGS = 1097
RPMTAG_DIRINDEXES = 1116
RPMTAG_BASENAMES = 1117
RPMTAG_DIRNAMES = 1118

# Dependency information
RPMTAG_PROVIDENAME = 1047
RPMTAG_REQUIREFLAGS = 1048
RPMTAG_REQUIRENAME = 1049
RPMTAG_REQUIREVERSION = 1050
RPMTAG_CONFLICTFLAGS = 1053
RPMTAG_CONFLICTNAME = 1054
RPMTAG_CONFLICTVERSION = 1055
RPMTAG_OBSOLETENAME = 1090
RPMTAG_PROVIDEFLAGS = 1112
RPMTAG_PROVIDEVERSION = 1113
RPMTAG_OBSOLETEFLAGS = 1114
RPMTAG_OBSOLETEVERSION = 1115

# Other information
RPMTAG_BUILDTIME = 1006
RPMTAG_BUILDHOST = 1007
RPMTAG_FILEVERIFYFLAGS = 1045
RPMTAG_CHANGELOGTIME = 1080
RPMTAG_CHANGELOGNAME = 1081
RPMTAG_CHANGELOGTEXT = 1082
RPMTAGS_OPTFLAGS = 1122
RPMTAGS_RHNPLATFORM = 1131
RPMTAG_PLATFORM = 1132



def __get_tags(values: Dict[str, Any]) -> Dict[str, int]:
    out = dict()
    for k, v in values.items():
        if not k.startswith('RPMTAG'):
            continue
        if type(v) == int:
            out[k] = v
    return out

ALL_RPM_TAGS = __get_tags(locals())
RPMTAGS = ALL_RPM_TAGS.values()
VALUES_TO_RPMTAGS = dict([(v, k) for k, v in ALL_RPM_TAGS.items()])

INSTALLATION_INFO_TAGS = (
    RPMTAG_PREIN,
    RPMTAG_POSTIN,
    RPMTAG_PREUN,
    RPMTAG_POSTUN,
    RPMTAG_PREINPROG,
    RPMTAG_POSTINPROG,
    RPMTAG_PREUNPROG,
    RPMTAG_POSTUNPROG
)

FILE_INFO_TAGS = (
    RPMTAG_OLDFILENAMES,
    RPMTAG_FILESIZES,
    RPMTAG_FILEMODES,
    RPMTAG_FILERDEVS,
    RPMTAG_FILEMTIMES,
    RPMTAG_FILEMD5S,
    RPMTAG_FILELINKTOS,
    RPMTAG_FILEFLAGS,
    RPMTAG_FILEUSERNAME,
    RPMTAG_FILEGROUPNAME,
    RPMTAG_FILEDEVICES,
    RPMTAG_FILEINODES,
    RPMTAG_FILELANGS,
    RPMTAG_DIRINDEXES,
    RPMTAG_BASENAMES,
    RPMTAG_DIRNAMES
)

DEPENDENCY_INFO_TAGS = (
    RPMTAG_PROVIDENAME,
    RPMTAG_REQUIREFLAGS,
    RPMTAG_REQUIRENAME,
    RPMTAG_REQUIREVERSION,
    RPMTAG_CONFLICTFLAGS,
    RPMTAG_CONFLICTNAME,
    RPMTAG_CONFLICTVERSION,
    RPMTAG_OBSOLETENAME,
    RPMTAG_PROVIDEFLAGS,
    RPMTAG_PROVIDEVERSION,
    RPMTAG_OBSOLETEFLAGS,
    RPMTAG_OBSOLETEVERSION
)